### ISSUE TITLE
Feature Request: Save keywords persistently

### ISSUE THREAD

**Issue by tbarkai** [brian-girko/multiple-highlight#1]
If I highlight words on page A, navigate to page B and then back to A - the highlight disappears. It would be very helpful if revisits to page A (especially from the history back button) would also preserve the highlights and search terms.

**Comment by brian-girko** [comment]
We can have a button to persist the highlights before closing the UI.

**Comment by brian-girko** [comment]
We are going to have two options:

1. Shift + click on the "x" button keeps the highlights for the current session.
2. There is a new option to control the persistence of the highlights.

**Comment by tbarkai** [comment]
Thanks for the quick response!
Unfortunately the fix doesn't work... Highlights still disappear when navigating to a new page and back.
Installed version is 0.1.1

**Comment by brian-girko** [comment]
I misunderstood your feature request then. I thought you mean when moving to another tab, not navigating to a new page. Unfortunately with the current limited set of permissions, we cannot act on a page when the toolbar button is not clicked. We can have a history though so that when the popup is opened on an already visited URL, the extension performs the last search. If this is something useful I can add the feature.

**Comment by tbarkai** [comment]
Thanks, Brian.
I think that that would do the trick.

**Comment by brian-girko** [comment]
we are going to have this new optional history feature as of the 0.1.2 release.
